### ISSUE TITLE
Connection strings are mostly undocumented [DOC101]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#110]
Submitted by: Arioch (arioch)

Connection strings are important, because they can be used for maintainance tasks like diagnostic errors, or selecting database file for repair attempts and such

So the documentation on CS providing for writing a parser would be quite an asset\.

I only found it in <http://www.firebirdsql.org/manual/qsg25-databases.html> and it lacks at least two things

1\) NetBEUI connection
2\) specification non\-default port in TCP connections

**Comment by mrotteveel** [comment]
Partially addressed by documentation of [`CREATE DATABASE`](https://www.firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-ddl-db-create).

**Comment by mrotteveel** [comment]
Also documented in ISQL documentation.
