### ISSUE TITLE
Syntax for Manage Nullability in Domains and Columns is wrong [DOC120]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#126]
Submitted by: Mark Junker (fubar-coder)

The documentation of Firebird 3\.0\.0 rc1 \(zip archive\) says that the nullability of a column is changed with the following instruction:

ALTER TABLE <table name\> ALTER <field name\> \[NOT\] NULL

The correct instruction would be:

ALTER TABLE <table name\> ALTER <field name\> \{ SET \| DROP \} NOT NULL

I guess that the syntax for domains is wrong too and therefore should be

ALTER DOMAIN <domain name\> \{ SET \| DROP \} NOT NULL

**Comment by mrotteveel** [comment]
Was already fixed
