### ISSUE TITLE
GRANT syntax in Firebird Language Reference incorrect [DOC125]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#130]
Submitted by: @mrotteveel

The syntax of GRANT \(privileges\) in the language reference is incorrect \(<http://www.firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-security-privs.html#fblangref25-security-privs-grant>\)\. It shows:

GRANT \{
  <privileges\> ON \[TABLE\] \{tablename \| viewname\} 
  \| EXECUTE ON PROCEDURE procname
      \}
TO <grantee\_list\>
  \[WITH GRANT OPTION\]\} \| \[\{GRANTED BY \| AS\} \[USER\] grantor\];

This implies that WITH GRANT OPTION and GRANTED BY are mutually exclusive which is not the case\. The correct syntax is:

GRANT \{
  <privileges\> ON \[TABLE\] \{tablename \| viewname\} 
  \| EXECUTE ON PROCEDURE procname
      \}
TO <grantee\_list\>
   \[WITH GRANT OPTION\] 
   \[\{GRANTED BY \| AS\} \[USER\] grantor\]

Note that I also removed an invalid \`\}\` after \[WITH GRANT OPTION\] and the trailing \`;\`\.

**Comment by mrotteveel** [comment]
This is already fixed in fblangref30, but not yet in fblangref25

**Comment by mrotteveel** [comment]
Fixed in fblangef25 as well.
