### ISSUE TITLE
Binary string literal missing from 2.5 language reference [DOC126]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#131]
Submitted by: @mrotteveel

The Firebird 2\.5 language reference, section literals \(<http://www.firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-structure-literals.html>\) and chapter Data Types and Subtypes \(<http://www.firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-datatypes.html>\) do not describe binary string literals\.

See also: [CORE1760](https://github.com/FirebirdSQL/firebird/issues?q=CORE1760+in%3Atitle)

**Comment by mrotteveel** [comment]
Fixed this myself while overhauling the documentation
