### ISSUE TITLE
Update Language Reference to reflect information about CORE-2505 [DOC128]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#133]
Submitted by: himajin100000_gmail.com (himajin100000)

Please include information about [CORE2505](https://github.com/FirebirdSQL/firebird/issues?q=CORE2505+in%3Atitle)
[CORE2505](https://github.com/FirebirdSQL/firebird/issues?q=CORE2505+in%3Atitle)
in the documentation for Firebird 2\.5 and for Firebird 3\.0
<http://firebirdsql.org/file/documentation/reference_manuals/fblangref25-en/html/fblangref25-functions-scalarfuncs.html#fblangref25-funcs-tbl-acos>

so that it would be helpful to the following LibreOffice bug report\.
<https://bugs.documentfoundation.org/show_bug.cgi?id=104894>

**Comment by mrotteveel** [comment]
Valid input ranges of these functions are documented.
