### ISSUE TITLE
There is no -m in gfix [DOC140]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#143]
Submitted by: @WarmBooter

Fix the document <https://www.firebirdsql.org/pdfmanual/html/gfix-dbverify.html>
It says

The option required to fix a corrupted database is the gfix \-m\[end\] command\. However, it cannot fix all problems and may result in a loss of data\. It all depends on the level of corruption detected\. The command is:
gfix \-m\[end\] database\_name

Vlad pointed me that there is no "\-m" for gfix\. The correct should be "\-me" \(as displayed by Firebird 3's gfix \-?\)\.

**Comment by mrotteveel** [comment]
This was fixed during the overhaul of the documentation
