### ISSUE TITLE
isql show DB command was extended in Firebird 3.0 [DOC141]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#144]
Submitted by: Arioch (arioch)

"show database" command was extended after [CORE5063](https://github.com/FirebirdSQL/firebird/issues?q=CORE5063+in%3Atitle)

However <https://firebirdsql.org/manual/isql-show.html#d0e37518> still shows FB 2\.5 example \(judging by ODS\) with no mention of extra data introduced later\.

**Comment by mrotteveel** [comment]
The documentation doesn't itemize all data listed by `show database`, and I don't think it is necessary to make this explicit.
