### ISSUE TITLE
Sql query behavior not as expected [DOC142]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#145]
Submitted by: Paweł Krzyżanowski (zpksoft)

in
<https://firebirdsql.org/manual/nullguide-predicates.html>

is code:
```sql
SELECT Farmer FROM Farms WHERE EXISTS
  (SELECT * FROM Landowners
   WHERE Landowners.Name = Farms.Farmer)
```   
but not working:
```sql
SELECT Farmer FROM Farms WHERE EXISTS
  (SELECT * FROM Landowners
   WHERE Landowners.Name CONTAINING Farms.Farmer)
```

\(and not working with like, result is NULL\)

For example 'LISA' as Farmer and 'MONALISA' as Landowners.Name
'MONALISA' CONTAINING 'LISA' but EXISTS in this query returns NULL\.
Alone EXISTS returns correct dataset\.

**Comment by mrotteveel** [comment]
Without more details, this is not really answerable. It also looks like a support question which would be more suitable for https://groups.google.com/g/firebird-support
