### ISSUE TITLE
PSQL grammar [DOC143]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#146]
Submitted by: softhard_at (softhard_at)

I have to create PSQL parser \(syntax analyzer\) for procedures/functions/triggers bodies\.
As input the parser should have a file containing the grammar of Firebird PSQL\.
Where can I find the grammar of PSQL in any common standard \(e\.g\. antlr, yacc, bison\)?

**Comment by mrotteveel** [comment]
The grammar of Firebird can be found in https://github.com/FirebirdSQL/firebird/blob/master/src/dsql/parse.y (this combines both PSQL and DSQL)
