### ISSUE TITLE
Changing Dialect 1 to 3 [DOC144]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#147]
Submitted by: softhard_at (softhard_at)

Is detailed documentation available  for migration from Dialect 1 to Dialect 3\.
Any scripts, tools sofware \(even 3rd party\), etc?

**Comment by mrotteveel** [comment]
Documentation for migration of dialect 1 to dialect 3 is covered in the InterBase 6.0 Getting Started, available from InterBase 6.0 Manuals, _Full Set_ from https://firebirdsql.org/en/reference-manuals/.
