### ISSUE TITLE
Syntax of SUBSTRING( ... SIMILAR ...) in FB3, FB4 [DOC146]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#148]
Submitted by: prenosil (prenosil)

The examples in README\.substring\_similar\.txt are correct, like
substring\('abcabc' similar 'a#&#x2060;"bcab#&#x2060;"c' escape '#&#x2060;'\)

But the syntax description in this document is wrong:
  <regular expression substring\> ::= SUBSTRING\(<value\> FROM <similar pattern\> ESCAPE <escape character\>\)

Also the syntax in FB3 Release Notes is wrong
  SUBSTRING\(<string\> \[NOT\] SIMILAR TO <pattern\> ESCAPE <char\>\)
\(both NOT and TO\)

**Comment by mrotteveel** [comment]
Fixed recently in:

- https://github.com/FirebirdSQL/firebird/commit/6e685c3f82ead8c6d590fe921baf288ac2bd4332 (master)
- https://github.com/FirebirdSQL/firebird/commit/2af0689450dafa2528ab8c20ab88eb7ebf7c92d4 (B3_0_Release)
- https://github.com/FirebirdSQL/firebird-documentation/commit/4aa7753a1dcfa4082fc8b739791a876fc18a8b52 (rlsnotes30 and fblangref30)
