### ISSUE TITLE
on connect trigger transation parameters

### ISSUE THREAD

**Issue by EPluribusUnum** [FirebirdSQL/firebird-documentation#163]
Hi!

Please put on connect trigger documetation that is uses default transasction parameters (concurrency, write, wait).
see https://github.com/FirebirdSQL/firebird/issues/6982#issuecomment-929912442

Thank You!

**Comment by mrotteveel** [comment]
Thanks. I added an explicit mention of the isolation level in DDL and PSQL chapters of fblangref30 and fblangref30.
