### ISSUE TITLE
RECREATE TABLE is acceptable in embedded mode

### ISSUE THREAD

**Issue by hamacker** [FirebirdSQL/firebird-documentation#171]
The link
https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-ddl-tbl-recreate
says that RECREATE TABLE is not acceptable for Embedded SQL (ESQL), but it is!
I try and it's OK.

**Comment by mrotteveel** [comment]
Could you provide an example of it in ESQL?

**Comment by hamacker** [comment]
Of curse!
In Lazarus using zeos, I already have one:
https://github.com/gladiston/lazdemos_gsl.git
in lazdemos_gsl/lazdemo_transacoes
Is a sample project that create a database and connect using both methods,
if you can connect using embeded method or client/servir, 'recreate table'
will be used to create TEST_TIL and add registries.
If you just see a code, line #465 in view.principal.pas file.

Em ter., 1 de mar. de 2022 às 05:07, Mark Rotteveel <
***@***.***> escreveu:

**Comment by mrotteveel** [comment]
That example doesn't use ESQL (Embedded SQL), it uses DSQL (Dynamic SQL). ESQL is a special dialect of Firebird SQL that is embedded in code, and transformed by a preprocessor before compilation.

I guess you're using the Firebird Embedded database engine. Though both use the term _embedded_ they are not related.

**Comment by hamacker** [comment]
Yes, I am using Firebird Embedded database engine.
I think that method are the same ESQL, is not?

**Comment by mrotteveel** [comment]
No, it is not. You're using DSQL (Dynamic SQL), the "normal" SQL dialect of Firebird. As I said, ESQL is a special embedded language that is transformed using a preprocessor. It is hardly ever used these days.
