### ISSUE TITLE
MON$TIMESTAMP description for FB4 missing timezone in datatype

### ISSUE THREAD

**Issue by cincuranet** [FirebirdSQL/firebird-documentation#172]
For example [here](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref-appx05-transacs) the `MON$TIMESTAMP` should be `TIMESTAMP WITH TIME ZONE`.

**Comment by mrotteveel** [comment]
Updated en and de version, but not yet uploaded as I currently can't access the upload site.

**Comment by mrotteveel** [comment]
Updated version is now uploaded
