### ISSUE TITLE
Setup command line switches

### ISSUE THREAD

**Issue by MartinKoeditz** [FirebirdSQL/firebird-documentation#175]
I couldn't find anything about the setup command line switches. Should we integrate it somewhere in the docs?
I found the origin documentation here: https://ib-aid.com/en/articles/firebird-3-setup-command-line-parameters/

**Comment by mrotteveel** [comment]
This doesn't fit in any of the existing docs, so it would require a "new" doc. As an aside, your link is not the original source of the doc. The original is in the Firebird sources, specifically https://github.com/FirebirdSQL/firebird/blob/master/builds/install/arch-specific/win32/installation_scripted.txt, and the intent it is maintained together with the installer itself.

Personally, I think it is better to leave it there and not duplicate the effort. That said, feel free to start it.

**Comment by mrotteveel** [comment]
Or, if you want to improve the existing one, consider to provide pull requests against the docs in the firebird repository.
