### ISSUE TITLE
firebird-40-language-reference.pdf Deterministic function description

### ISSUE THREAD

**Issue by livius2** [FirebirdSQL/firebird-documentation#177]
firebird-40-language-reference.pdf
page 200/201 describe `Deterministic function`

In the example there is `rdb $ database` but should be `rdb$database` 
and also in last statement is:
`SELECT n, fn_t () FROM`
but should be
`SELECT n, fn_t () FROM t`

on the page 267 also `rdb $ database` but should be `rdb$database`

**Comment by mrotteveel** [comment]
@livius2 Documentation issues should be created in https://github.com/FirebirdSQL/firebird-documentation/issues, I have moved the issue.

**Comment by mrotteveel** [comment]
Issues fixed in fblangref30 and fblangref40
