### ISSUE TITLE
Wrong alias in MERGE example (Release notes)

### ISSUE THREAD

**Issue by MartinKoeditz** [FirebirdSQL/firebird-documentation#187]
I think there is an error in the example of section 
Support for WHEN NOT MATCHED BY SOURCE in the MERGE statement

```
MERGE
	INTO customers c
	USING new_customers nc
	ON (c.id = nc.id)
	WHEN MATCHED THEN
		UPDATE SET	name = cd.name
	WHEN NOT MATCHED BY SOURCE THEN
		DELETE
```

The alias in `UPDATE SET	name = cd.name` is wrong, isn't it?

Ref: [FB 5.0 Relase Notes](https://firebirdsql.org/file/documentation/release_notes/html/en/5_0/rlsnotes50.html#rnfb50-dml-skip-locked)

**Comment by mrotteveel** [comment]
Yes, looks like a typo. I'll fix it. Thanks.
