### ISSUE TITLE
[FB4] 5.7.2. ALTER TRIGGER has a bad "CREATE TRIGGER" link

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird-documentation#189]
Hi

https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-ddl-trgr-alter

When I click on "CREATE TRIGGER" link, I see "CREATE PROCEDURE" description

![image](https://github.com/FirebirdSQL/firebird-documentation/assets/4594554/a5cdc2e2-7466-4e11-8793-4522eae9657f)

**Comment by mrotteveel** [comment]
Thanks for reporting.

Fixed in:
* fblangref30: 1.17
* fblangref40: 2.9
* fblangref50: 0.6

Given this is a minor fix, I'll deploy this later when more fixes have accumulated in these versions.
