### ISSUE TITLE
[FB4] 5.7.2. ALTER TRIGGER. There can skip declaration of body

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird-documentation#190]
https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-ddl-trgr-alter

```
ALTER TRIGGER trigname
  [ACTIVE | INACTIVE]
  [{BEFORE | AFTER} <mutation_list>]
  [POSITION number]
  {<psql_trigger> | <external-module-body>}
```
FB4 can execute ALTER TRIGGER without any options.

<img width="178" alt="image" src="https://github.com/FirebirdSQL/firebird-documentation/assets/4594554/e3db88e9-1794-4f8a-afcb-70245af351e6">

So - `{<psql_trigger> | <external-module-body>}` is the optional part of this statement.

**Comment by mrotteveel** [comment]
This sounds like an implementation bug in Firebird to me, and not something which should be reflected in the syntax documentation.

**Comment by dmitry-lipetsk** [comment]
Russian documentation defines "ALTER TRIGGER" more clearly:

```
ALTER TRIGGER trigname
[ACTIVE | INACTIVE]
[{BEFORE | AFTER} <mutation_list>]
[POSITION number]
[SQL SECURITY {DEFINER | INVOKER} | DROP SQL SECURITY]
[<routine-body>]
```
_But it has another problem here :)_

If I understand correctly, the declaration {<psql_trigger> | <external-module-body>} means that either you define **psql_trigger** or you define **external-module-body**

Of course, I can go to declare empty **psql_trigger** when I want to skip declaration of **external-module-body**

I'm not sure that the parser of FB will agree with it, but a human can say that it is great idea :)

**Comment by mrotteveel** [comment]
That syntax documentation is incorrect, because the `SQL SECURITY` clause only applies to PSQL triggers, not for external module triggers

**Comment by mrotteveel** [comment]
The current syntax is a bit of a tradeoff, but is intended to reflect that you can only use `<sql_security>` for PSQL triggers.

If you go a more formal route, the actual syntax in Firebird is buggy, and this case should not have been allowed. It is the result of the third alternative of `alter_trigger_clause` in `parse.y` being:

`symbol_trigger_name trigger_active trigger_type_opt trigger_position trg_sql_security_clause`, while `trg_sql_security_clause` would have been better called `trg_sql_security_clause_opt` as it is optional, while the intent seems to be that it is required in that alternative.

**Comment by mrotteveel** [comment]
I'll make it `[{<psql_trigger> | <external-module-body>}]`.
