### ISSUE TITLE
Language reference: wrong description of RDB$INDICES.RDB$FOREIGN_KEY field

### ISSUE THREAD

**Issue by aafemt** [FirebirdSQL/firebird-documentation#191]
This is not the constraint's name but name of index on master table this key is referencing to.

**Comment by mrotteveel** [comment]
The InterBase 6.0 Language Reference also documents it as _"Name of `FOREIGN KEY` constraint for which the index is implemented"_. IIRC, historically, the index was named the same as the foreign key constraint.

**Comment by mrotteveel** [comment]
I see you're right, so this has been documented incorrectly for a long time... I'll update fblangref25 - fblangref50.

**Comment by mrotteveel** [comment]
Fixed in fblangref25 - fblangref50, published fblangref25 - fblangref40.

Thanks for reporting.
