### ISSUE TITLE
[FB4] Description of RDB$FUNCTION_ARGUMENTS::RDB$MECHANISM

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird-documentation#192]
This column can also contain the following values:
- **4** for SCALAR_ARRAY
- **5** for REFERENCE_WITH_NULL

**Comment by mrotteveel** [comment]
Thanks, I'll add it when I have time.

**Comment by mrotteveel** [comment]
BTW: Is this only for Firebird 4+ or also for older versions?

**Comment by dmitry-lipetsk** [comment]
These constants were added in FB v2.0, if I understand correctly.

FB2 source (types.h):
```c++
	TYPE("BY_VALUE", 0, nam_mechanism)
	TYPE("BY_REFERENCE", 1, nam_mechanism)
	TYPE("BY_VMS_DESCRIPTOR", 2, nam_mechanism)
	TYPE("BY_ISC_DESCRIPTOR", 3, nam_mechanism)
	TYPE("BY_SCALAR_ARRAY_DESCRIPTOR", 4, nam_mechanism)
	TYPE("BY_REFERENCE_WITH_NULL", 5, nam_mechanism)
```
FB1.5.4.4910 source (types.h):
```c++
	TYPE("BY_VALUE", 0, nam_mechanism)
	TYPE("BY_REFERENCE", 1, nam_mechanism)
	TYPE("BY_VMS_DESCRIPTOR", 2, nam_mechanism)
	TYPE("BY_ISC_DESCRIPTOR", 3, nam_mechanism)
	TYPE("BY_SCALAR_ARRAY_DESCRIPTOR", 4, nam_mechanism)
```
Although FB1.5 has SCALAR_ARRAY-constant, it does not support the creation of UDF with such arguments (i tested this).

**Comment by mrotteveel** [comment]
Given the language references only start at 2.5, the behaviour for Firebird 1.5 is not important :)

**Comment by dmitry-lipetsk** [comment]
Ok :)

пн, 13 нояб. 2023 г. в 17:06, Mark Rotteveel ***@***.***>:

**Comment by mrotteveel** [comment]
Added to fblangref25 - fblangref50; this will be published at a later time (hoping/waiting for more changes to accumulate).
