### ISSUE TITLE
Formatting of value list of RDB$FUNCTION_ARGUMENTS - RDB$FIELD_TYPE in language reference is wrong

### ISSUE THREAD

**Issue by usystem** [FirebirdSQL/firebird-documentation#194]
RDB$FUNCTION_ARGUMENTS - RDB$FIELD_TYPE 
error
29 - TIMESTAMP WITH WITH TIME ZONE 35 -
TIMESTAMP

**Comment by mrotteveel** [comment]
OK, I see that the formatting is wrong. I'll fix that.

**Comment by mrotteveel** [comment]
Fixed in fblangref40 and fblangref50, will be published later when more fixes have accumulated. Thanks for reporting.

**Comment by usystem** [comment]
Not only formatting. Double with  in TIMESTAMP WITH WITH TIME ZONE

**Comment by mrotteveel** [comment]
Thanks, fixed that too (and some other occurrences of WITH WITH).
