### ISSUE TITLE
[langref] List of system tables looks incorrectly

### ISSUE THREAD

**Issue by dmitry-lipetsk** [FirebirdSQL/firebird-documentation#195]
Hello,

https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref40/firebird-40-language-reference.html#fblangref40-appx04-systables

The list of system tables in left side catalog is displayed incorrectly

<img width="220" alt="image" src="https://github.com/FirebirdSQL/firebird-documentation/assets/4594554/81e0a284-1ad3-457d-b7e8-a6cb29382b63">

Chrome v119.0.6045.200

**Comment by mrotteveel** [comment]
Thanks, I'm aware of the problem, but I haven't found a solution yet. It has something to do with the font-loading or font-size and the script building the navigation calculating a wrong size somewhere. To be honest, I didn't find it important enough to invest a lot of time and energy in.

I'm happy to accept a PR with a fix.

**Comment by Norpa** [comment]
#tocbot .is-collapsible {
    /* max-height: 1000px; */
    overflow: hidden;
}
:-)

**Comment by mrotteveel** [comment]
Fix will be deployed with the next release of a language reference. I don't think the other manuals are affected, but otherwise I'll redeploy them as well if I hear about it.

Thanks @dmitry-lipetsk  for reporting and @Norpa for this fix/
