### ISSUE TITLE
`RDB$INDICES` new columns are missing from the Firebird 5.0 Docs

### ISSUE THREAD

**Issue by fdcastel** [FirebirdSQL/firebird-documentation#198]
From [Firebird 5.0 Release Candidate 2 Release Notes](https://firebirdsql.org/file/documentation/release_notes/html/en/5_0/rlsnotes50.html#rnfb50-apiods-new-syscols)

> Columns `RDB$CONDITION_SOURCE` and `RDB$CONDITION_BLR` were added to the system table `RDB$INDICES`,
they belong to the partial indices feature.

Unfortunately, they are missing in [the current docs](https://firebirdsql.org/file/documentation/html/en/refdocs/fblangref50/firebird-50-language-reference.html#fblangref-appx04-indices).

**Comment by mrotteveel** [comment]
Thanks! I somehow missed that when going through the release notes to update the docs. I committed a fix, but have not yet published it. I'm waiting for more changes to accumulate before publishing.

P.S. You reported this originally to the [firebird](https://github.com/FirebirdSQL/firebird) repository. Please report issues like this to the [firebird-documentation](https://github.com/FirebirdSQL/firebird-documentation) repository.

**Comment by fdcastel** [comment]
Thanks @mrotteveel !

> Please report issues like this to the [firebird-documentation](https://github.com/FirebirdSQL/firebird-documentation) repository.

Sorry. My bad. Understood! 👍
