### ISSUE TITLE
Mistype in SEC$USERS description

### ISSUE THREAD

**Issue by aafemt** [FirebirdSQL/firebird-documentation#202]
Language Reference v4 (may be others too) has this note in description of SEC$USERS table:

> Multiple users **van** exist with the same username, each managed by a different authentication plugin.

Perhaps "can" was meant.

**Comment by mrotteveel** [comment]
Thanks. Fixed in fblangref30 - fblangref50. 

I haven't deployed it yet, that will happen when there have been more changes.
