### ISSUE TITLE
ISQL documentation shows SET option EXEC_DISPLAY_PATH, but it's SET EXEC_PATH_DISPLAY

### ISSUE THREAD

**Issue by bujhm1987** [FirebirdSQL/firebird-documentation#209]
Error in document https://firebirdsql.org/file/documentation/html/en/firebirddocs/isql/firebird-isql.html#isql-set-exec-path-display
Parameter SET EXEC_PATH_DISPLAY!!!

SQL> SET EXEC_PATH_DISPLAY BLR;
SQL> SET EXEC_DISPLAY_PATH BLR;
Statement failed, SQLSTATE = 42000
Dynamic SQL Error
-SQL error code = -104
-Token unknown - line 1, column 5
-EXEC_DISPLAY_PATH
SQL>

**Comment by mrotteveel** [comment]
Thanks for reporting, the fix should be available online shortly.
