### ISSUE TITLE
sql code : 904 [DOC55]

### ISSUE THREAD

**Issue by firebird-automations** [FirebirdSQL/firebird-documentation#62]
Submitted by: Arul Jose. R (aruljose)

My firebird installation is throwing 904 sql code\. Could not find any description for this in firebird documentation\. 
What does this SQL code mean?

C:\\arul\\firebird\\Firebird\-2\.1\.3\.18185\-0\_Win32\\bin\>isql \-u SYSDBA \-p masterkey
Use CONNECT or CREATE DATABASE to specify a database
SQL\> CREATE DATABASE 'c:\\arul\\firebird\\utftester1\.fdb' user 'SYSDBA' password 'masterkey';
Statement failed, SQLCODE = \-904
unavailable database
C:\\arul\\firebird\\Firebird\-2\.1\.3\.18185\-0\_Win32\\bin\>fbserver\.exe

C:\\arul\\firebird\\Firebird\-2\.1\.3\.18185\-0\_Win32\\bin\>isql \-u SYSDBA \-p masterkey \.\.\\security2\.fdb
Statement failed, SQLCODE = \-904
unavailable database
Use CONNECT or CREATE DATABASE to specify a database

**Comment by DanCypress** [comment]
I guess, either the server isn't running or the [local protocol](https://detroithoodcleaning.com) isn't working correctly.
