### ISSUE TITLE
En dash within programlisting not displayed correctly in HTML [DOC68]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#76]
Submitted by: @paulvink

In the HTML output, en dashes \(Unicode 2013h = 8211d\) are displayed incorrectly when they occur in a programlisting element\.

Observed in Firefox and IE, under Windows 7\. Possibly due to limitations of the fixed\-width font\.

**Comment by mrotteveel** [comment]
No longer relevant after overhaul of documentation
