### ISSUE TITLE
FB4 Release Notes should indicate that revised CREATE TRIGGER (SQL2003) syntax is not backwards compatible with older versions [DOC145]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#81]
Submitted by: Tony Whyman (twhyman)

See [CORE6243](https://github.com/FirebirdSQL/firebird/issues?q=CORE6243+in%3Atitle) and [CORE5545](https://github.com/FirebirdSQL/firebird/issues?q=CORE5545+in%3Atitle) for background discussion\.

The SQL2003 variant of the CREATE TRIGGER syntax has changed in Firebird 4 so that the "POSITION" clause must now come after the "ON <relation name\>" clause instead of preceding it as was the case in Firebird 2\.5 and Firebird 3\.x\. SQL statements that successfully used this variant in earlier versions will be rejected by Firebird 4 as invalid syntax \(token unknown \- POSITION\)\. The Firebird 2\.5 language reference specifies:

<relation\_trigger\_sql2003\> ::=
  \[ACTIVE \| INACTIVE\]
  \{BEFORE \| AFTER\} <mutation\_list\>
  \[POSITION number\]
  ON \{tablename \| viewname\}

Firebird 4 effectively changes the syntax specification to

<relation\_trigger\_sql2003\> ::=
  \[ACTIVE \| INACTIVE\]
  \{BEFORE \| AFTER\} <mutation\_list\>
  ON \{tablename \| viewname\}
  \[POSITION number\]

[CORE5545](https://github.com/FirebirdSQL/firebird/issues?q=CORE5545+in%3Atitle) declares that this a bug fix despite both Firebird 2\.5 and Firebird 3 being compliant with the Firebird 2\.5 language reference manual\. The "POSITION" clause is understood to be a Firebird extension rather than an SQL standard and hence the language reference may be viewed as the original specification\. Both Firebird 2\.5 and Firebird 3 are compliant with the specification and hence this should not be identified as a bug\. [CORE5545](https://github.com/FirebirdSQL/firebird/issues?q=CORE5545+in%3Atitle) is a change to the Firebird SQL syntax specification\.

The revised CREATE TRIGGER syntax should be declared in the release notes both in chapter 8 \(DDL\) and in chapter 12 \(Compatibility Issues\) so that users are correctly informed about this change to the Firebird SQL specification\.

**Comment by mrotteveel** [comment]
@dyemanov Can you check if this is still relevant?

**Comment by mrotteveel** [comment]
Verified, Firebird allows `POSITION` in both positions.
