### ISSUE TITLE
README.keywords, SQLSTATE, FB2.5.1 [DOC148]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#84]
Submitted by: @ibprovider

Hello,

README\.keywords says that "SQLSTATE" is new reserved word of FB3\.0\.

By fact \- it is new reserved word of FB2\.5\.1

I think, need correct the README\.keywords file \(add new section for FB2\.5\.1\)\.

**Comment by mrotteveel** [comment]
As Firebird 2.5 is end of life, this will not get updated.
