### ISSUE TITLE
Incorrect ORDER BY clause in SELECT UNION syntax sample [DOC76]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#86]
Submitted by: arni (arni)

Firebird 2\.5 Language Reference Update, 
8 Oct 2011, 
document version 1\.1, 
page 95

Syntax:
\.\.\.
With a UNION:

SELECT \[FIRST p\] \[SKIP q\] <columns\> FROM \.\.\.
\[WHERE \.\.\.\]
\[ORDER BY \.\.\.\]
UNION \[ALL \| DISTINCT\]
SELECT \[FIRST r\] \[SKIP s\] <columns\> FROM \.\.\.
\[WHERE \.\.\.\]
\[ORDER BY \.\.\.\]
ROWS <m\> \[TO <n\>\]

ORDER BY clause before UNION ALL is illegal in this sample\.

**Comment by mrotteveel** [comment]
This has been fixed in the language references, but not in the language reference update. As we no longer maintain the language reference update, I'm going to close this.
