### ISSUE TITLE
consider not taking the char '&' in a sysdba password. It will cause some calamities [DOC88]

### ISSUE THREAD

**Issue by firebird-issue-importer** [FirebirdSQL/firebird-documentation#98]
Submitted by: Werner Poschen (vernond)

Changing a sysdba password from masterke\(y\) to you&me will be accepted doing this by
   gsec  modify sysdba \-pw\.you&me
But then there is not any longer the possibility to log in as sysdba using the firebird admin tools, including isql\.

What i've tried out \-only shown with  gsec:
gsec \-user sysdba \-password you&me     ==\> name  & pasword not defined
escaping it
gsec \-user sysdba \-password you&&me     ==\> name  & pasword not defined
qouting it
gsec \-user sysdba \-password 'you&me'    ==\> name & password not defined; command "dba" wrong or not found
escaping and quoting
gsec \-user sysdba \-password 'you&&me'  ==\> name  & pasword not defined
doubleqoutes
gsec \-user sysdba \-password "you&&me"     ==\> name  & pasword not defined

So perhaps the documentation could be updated especiallly 'what chars are allowed in passwords'\.
Thanks vernond

**Comment by mrotteveel** [comment]
Using `&` in passwords is perfectly allowed, and works (at least in recent versions, not sure if that was the case when this issue was reported). However some shells/command prompt might require explicit quoting or escaping to allow its presence in a command line string.
